### ISSUE TITLE
控制不了滚动方向

### ISSUE THREAD

**Issue by qqqaa123123** [CaniceZ/notice-bar-vue#1]

**Comment by CaniceZ** [comment]
感谢反馈，暂不支持，近日加上相关配置

**Comment by CaniceZ** [comment]
已支持纵向滚动
![image](https://github.com/user-attachments/assets/edb85ee4-1787-4aec-95a5-29bc2514c8d5)

**Comment by qqqaa123123** [comment]
大佬我其实是想要从左往右滚动，现在默认是从右往左滚动，这个能不能搞个变量控制下🙏

**Comment by CaniceZ** [comment]
> 大佬我其实是想要从左往右滚动，现在默认是从右往左滚动，这个能不能搞个变量控制下🙏

有两点不合理：1、人类阅读习惯是从左到右，向右滚动容易出现后半部分内容看不到（nutui，uview，antd，vant等通知栏组件都不支持）；2、技术实现上需先将滚动的初始位置从0改到内容区域的中间，此时就需要先获取到宽度再执行动画存在第一帧延迟
若真需要实现此需求可以copy我源码到自己项目（components/notice-bar）进行修改
![image](https://github.com/user-attachments/assets/b07efbd2-dba1-4f27-865a-30f7276075ae)

**Comment by qqqaa123123** [comment]
好的谢谢。其实我现在的需求不是文字滚动，而是很多个元素滚动，类似于这样
![image](https://github.com/user-attachments/assets/45769f68-b789-4b7d-b4f4-0f263da7941b)
